# Generated by Django 5.1.4 on 2025-01-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_password_users_role_alter_users_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
