# Generated by Django 5.1.4 on 2025-01-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(default='user', max_length=10),
        ),
    ]
