# Generated by Django 5.1.4 on 2025-01-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('clas', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
