# Generated by Django 5.1.4 on 2025-01-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(0, 'Food'), (1, 'Not food')], default=0, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='clas',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(0, 'Food'), (1, 'Not food')], default=0),
        ),
    ]
